/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;
import java.sql.*;
import DAO.Conexao;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author Pichau
 */
public class TelaGerenciarProduto extends javax.swing.JFrame {
     private int product_pk = 0;
     private int totalQuantidade = 0;
     
    /**
     * Creates new form GerenciarProduto
     */
    public TelaGerenciarProduto() {
        initComponents();
        setLocationRelativeTo(null);
    }

    private void getAllCategory(){
        try{
            Connection con = Conexao.getCon();
            Statement st =  con.createStatement();
            ResultSet rs =st.executeQuery("Selecione as categorias");
            ComboBoxProduto.removeAllItems();
            while(rs.next()){
                ComboBoxProduto.addItem(rs.getString("Categorias")+"-"+rs.getString("nome"));
                //teste categoria
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private boolean validateFields(String formType){
        if(formType.equals("edit")&& !txtNomeProduto.getText().equals("")&& !txtPrecoProduto.getText().equals("")&& !txtDescricaoProduto.getText().equals("")){
            return false;
        }    
        else if(formType.equals("new")&& !txtNomeProduto.getText().equals("")&& !txtQuantidadeProduto.getText().equals("")&& !txtPrecoProduto.getText().equals("")&& !txtDescricaoProduto.getText().equals("")){
            return false;
        }else{
            return true;
        }     
            
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProdutos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ComboBoxProduto = new javax.swing.JComboBox<>();
        txtNomeProduto = new javax.swing.JTextField();
        txtQuantidadeProduto = new javax.swing.JTextField();
        txtPrecoProduto = new javax.swing.JTextField();
        txtDescricaoProduto = new javax.swing.JTextField();
        btnSalvarProduto = new javax.swing.JButton();
        btnAtualizarProduto = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnRemoverProduto = new javax.swing.JButton();

        jTextField4.setText("jTextField1");

        jTextField5.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        tableProdutos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "QUANTIDADE", "DESCRIÇÃO", "NOME CATEGORIA"
            }
        ));
        tableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProdutos);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("GERENCIAR PRODUTO");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("NOME");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("QUANTIDADE");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("PREÇO");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("DESCRIÇÃO");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("CATEGORIA");

        ComboBoxProduto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ComboBoxProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxProdutoActionPerformed(evt);
            }
        });

        txtNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProdutoActionPerformed(evt);
            }
        });

        txtQuantidadeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeProdutoActionPerformed(evt);
            }
        });

        txtPrecoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoProdutoActionPerformed(evt);
            }
        });

        txtDescricaoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoProdutoActionPerformed(evt);
            }
        });

        btnSalvarProduto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSalvarProduto.setText("SALVAR");
        btnSalvarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarProdutoActionPerformed(evt);
            }
        });

        btnAtualizarProduto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAtualizarProduto.setText("ATUALIZAR");
        btnAtualizarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarProdutoActionPerformed(evt);
            }
        });

        btnFechar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnFechar.setText("FECHAR");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnRemoverProduto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRemoverProduto.setText("REMOVER");
        btnRemoverProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalvarProduto)
                                .addGap(18, 18, 18)
                                .addComponent(btnAtualizarProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRemoverProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFechar))
                            .addComponent(ComboBoxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addComponent(txtQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComboBoxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAtualizarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoverProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //CAMPO PARA DIGITAR A QUANTIDADE DE PRODUTOS
    private void txtQuantidadeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeProdutoActionPerformed

        
    }//GEN-LAST:event_txtQuantidadeProdutoActionPerformed

    //CAIXA PARA SELECIONAR A CATEGORIA DO PRODUTO 
    private void ComboBoxProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxProdutoActionPerformed

        
    }//GEN-LAST:event_ComboBoxProdutoActionPerformed

    //CAMPO PARA DIGITAR O PREÇO DOS PRODUTOS
    private void txtPrecoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoProdutoActionPerformed

        
    }//GEN-LAST:event_txtPrecoProdutoActionPerformed

    //CAMPO PARA DIGITAR O NOME DO PRODUTO
    private void txtNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProdutoActionPerformed

        
    }//GEN-LAST:event_txtNomeProdutoActionPerformed

    //CAMPO PARA DIGITAR A DESCRIÇAO DO PRODUTO
    private void txtDescricaoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoProdutoActionPerformed
 
        
    }//GEN-LAST:event_txtDescricaoProdutoActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnRemoverProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverProdutoActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new TelaGerenciarProduto().setVisible(true);
        
    }//GEN-LAST:event_btnRemoverProdutoActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        getAllCategory();
        DefaultTableModel model = (DefaultTableModel) tableProdutos.getModel();
        try{
            Connection con = Conexao.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("selecione os produtos da categoria!");
            while(rs.next()){
                model.addRow(new Object[]{rs.getString("produto_pk"),rs.getString("nome"),rs.getString("quantidade"),rs.getString("preço"),rs.getString("descrição"),rs.getString("categoria"),rs.getString(0)});
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        btnAtualizarProduto.setEnabled(false);
        
    }//GEN-LAST:event_formComponentShown

    private void btnSalvarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarProdutoActionPerformed
        // TODO add your handling code here:
        String nome = txtNomeProduto.getText();
        String quantidade = txtQuantidadeProduto.getText();
        String preco = txtPrecoProduto.getText();
        String descricao = txtDescricaoProduto.getText();
        String categoria = (String) ComboBoxProduto.getSelectedItem();
        String categoriaId[] = categoria.split("-",0);
        if(validateFields("new")){
            JOptionPane.showMessageDialog(null, "todos os arquivos requeridos");
        }
        else{
            try{
                Connection con = Conexao.getCon();
                PreparedStatement ps = con.prepareStatement("insira os produtos(nome, quantidade,preço,categoria,descrição)");
                ps.setString(1,nome);
                ps.setString(2,preco);
                ps.setString(3,quantidade);
                ps.setString(4,descricao);
                ps.setString(5,categoriaId[0]);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Produto adicionado com sucesso");
                setVisible(false);
                new TelaGerenciarProduto().setVisible(true);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnSalvarProdutoActionPerformed

    private void tableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProdutosMouseClicked
        // TODO add your handling code here:
        int index = tableProdutos.getSelectedRow();
        TableModel model = tableProdutos.getModel();
        String id = model.getValueAt(index,0).toString();
        product_pk = Integer.parseInt(id);
        
        String nome = model.getValueAt(index, 1).toString();
        txtNomeProduto.setText(nome);
        
        String quantidade = model.getValueAt(index, 2).toString();
        txtQuantidadeProduto.setText("adicionar quantidade");
        totalQuantidade = Integer.parseInt(quantidade);
        
        String preco = model.getValueAt(index, 3).toString();
        txtPrecoProduto.setText(preco);
        
        String descricao = model.getValueAt(index, 4).toString();
        txtDescricaoProduto.setText(descricao);
        
        ComboBoxProduto.removeAllItems();
        String categoriaId = model.getValueAt(index, 5).toString();
                
        String categoriaNome = model.getValueAt(index, 6).toString();
        ComboBoxProduto.addItem(categoriaId+"-"+categoriaNome);
        
                try{
            Connection con = Conexao.getCon();
            Statement st =  con.createStatement();
            ResultSet rs =st.executeQuery("Selecione as categorias");
            
            while(rs.next()){
                if(Integer.parseInt(categoriaId) != rs.getInt(1)){
                    ComboBoxProduto.addItem(rs.getString("Categorias")+"-"+rs.getString("nome"));
                }
                //teste categoria
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        btnSalvarProduto.setEnabled(true);
    }//GEN-LAST:event_tableProdutosMouseClicked

    private void btnAtualizarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarProdutoActionPerformed
        // TODO add your handling code here:
         String nome = txtNomeProduto.getText();
        String quantidade = txtQuantidadeProduto.getText();
        String preco = txtPrecoProduto.getText();
        String descricao = txtDescricaoProduto.getText();
        String categoria = (String) ComboBoxProduto.getSelectedItem();
        String categoriaId[] = categoria.split("-",0);
        if(validateFields("edit")){
            JOptionPane.showMessageDialog(null, "todos os arquivos requeridos");
        }
        else{
            try{
                if(!quantidade.equals("")){
                    totalQuantidade= totalQuantidade+Integer.parseInt(quantidade);
                }
                Connection con = Conexao.getCon();
                PreparedStatement ps = con.prepareStatement("produtos salvos!");
                ps.setString(1,nome);
                ps.setString(2,preco);
                ps.setInt(2,totalQuantidade);
                ps.setString(4,descricao);
                ps.setString(5,categoriaId[0]);
                ps.setInt(6, product_pk);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Produtos atualizados com sucesso");
                setVisible(false);
                new TelaGerenciarProduto().setVisible(true);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
    }//GEN-LAST:event_btnAtualizarProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerenciarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxProduto;
    private javax.swing.JButton btnAtualizarProduto;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnRemoverProduto;
    private javax.swing.JButton btnSalvarProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tableProdutos;
    private javax.swing.JTextField txtDescricaoProduto;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtPrecoProduto;
    private javax.swing.JTextField txtQuantidadeProduto;
    // End of variables declaration//GEN-END:variables
}
